// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleScheduler.Models;

namespace TempleScheduler.Migrations
{
    [DbContext(typeof(GroupDbContext))]
    [Migration("20210318152652_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("TempleScheduler.Models.AvailableTime", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeslots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TimeId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("TempleScheduler.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeslotsTimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.HasIndex("TimeslotsTimeId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TempleScheduler.Models.Group", b =>
                {
                    b.HasOne("TempleScheduler.Models.AvailableTime", "Timeslots")
                        .WithMany()
                        .HasForeignKey("TimeslotsTimeId");
                });
#pragma warning restore 612, 618
        }
    }
}
